import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import record from '../data/topcovidcountries.json'
// import Lottie from "lottie-react";
import { useState, useEffect, useRef } from "react";
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const [loader, setLoader] = useState(true);

    useEffect(() => {
      const timer = setTimeout(() => {
        setLoader(false);
      }, 750);
  
      return () => clearTimeout(timer);
    }, []);

    console.log(record);

  return (
    <>
      <Head>
        <title>Covid Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {loading && (
        <div className="flex justify-center items-center min-h-screen">
          <Lottie
            animationData={require("../../public/lottie-files/loading-dots.json")}
            style={{
              width: 500,
              height: 300,
            }}
          />
        </div>
      )} */}

  <div class="px-64 py-6">
        <div>
            <div class="flex items-center justify-between">
                <div>
                    {/* <img src="/Logo.png" alt=""/> */}
                    <h2 class="font-bold text-5xl text-purpleText z-50">Covid Tracker</h2>
                </div>
                <div class="flex items-center space-x-12 z-50">
                    {/* <a href="#" class="font-semibold">Sort by Country</a> */}
                    <Link href="/viewbycountry" class="border px-4 py-1.5 rounded-md border-black font-semibold">View by Country</Link>
                </div>
                <img src="/Decore.png" class="absolute right-0 top-0 " alt=""/>
            </div>
            <div class="pt-60 flex items-center">
                <div class="w-[450px]">
                    <div>
                        <div class="grid gap-4">
                            <div class="grid gap-4">
                                <span class="font-bold text-6xl text-purpleText z-50">
                                    View live 
                                    Coronavirus data 24/7
                                </span>
                            </div>
                            <div>
                                <span class="text-lightPurpleText">
                                    Built with kaggle's, you can sort through the latest statistic information about covid-19 cases around the globe.
                                </span>
                            </div>
                            <div class="flex items-center space-x-6">
                                <Link href="/viewbycountry" class="px-4 py-2.5 rounded-md bg-yellowColor text-textWhite">Find out more</Link>
                            </div>
                        </div>
                    </div>
                </div>
                <div>
                    <div class="absolute top-20">
                        <img src="/coronavirusblue.png" class="coronavirusblue" alt=""/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</>
)
}

